networks:
  proxynetwork:
    driver: bridge

services:
  openresty:
    image: hieupth/openresty
    container_name: openresty
    restart: always
    # Security: Run as non-root user
    user: 999:999
    # Security: Read-only root filesystem
    read_only: true
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/templates.d
    tmpfs:
      - /tmp:uid=999,gid=999,mode=755
      - /var/run:uid=999,gid=999,mode=755
      - /var/cache/nginx:uid=999,gid=999,mode=755
      - /etc/nginx/templates.d:uid=999,gid=999,mode=755
    # Security: Drop all capabilities
    cap_drop:
      - ALL
    # Security: No new privileges
    security_opt:
      - no-new-privileges:true
    networks:
      - proxynetwork
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
      - ~/ssl:/ssl:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
