# ------------------------------------------------------
# Security header configurations.
# ------------------------------------------------------
# Hide nginx version to prevent sniffing.
server_tokens off;
# Disable ETags to prevent inode attack.
etag off;
# Prevent XSS attack.
add_header X-XSS-Protection "1; mode=block" always;
# Prevent MIME sniffing.
add_header X-Content-Type-Options "nosniff" always;
# Prevent Click-jacking attack.
add_header X-Frame-Options "DENY" always;
# More XSS protection by enable CSP.
add_header Content-Security-Policy "
  default-src 'self'; 
  script-src 'self' 'unsafe-inline';
  style-src 'self' 'unsafe-inline';
  mg-src 'self' data: https:;
  font-src 'self';
  connect-src 'self';
  frame-ancestors 'none';
" always;

# ------------------------------------------------------
# Filter bad things.
# ------------------------------------------------------
# Malicious user agents
map $http_user_agent $blocked_agent {
  default 0;
  ~*malicious 1;
  ~*sqlmap 1;
  ~*nikto 1;
  ~*nessus 1;
  ~*nmap 1;
  ~*masscan 1;
  ~*zmap 1;
  ~*scanner 1;
  ~*scraper 1;
}
# Bad referers (spam sites)
map $http_referer $blocked_referer {
    default 0;
    ~*semalt.com 1;
    ~*darodar.com 1;
    ~*buttons-for-website.com 1;
    ~*make-money-online 1;
}
# Dangerous request methods
map $request_method $blocked_method {
  default 0;
  ~*^(TRACE|DELETE|PATCH)$ 1;
}