# ------------------------------------------------------
# TLS configuration
# ------------------------------------------------------
# HSTS for HTTPS (uncomment when using SSL)
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
# Enable TLS to prevent Heartbleed.
ssl_protocols TLSv1.2 TLSv1.3;
# Enable TLS cache to reduce handshake time.
ssl_session_cache shared:SSL:5m;
ssl_session_timeout 20m;
ssl_session_tickets off;
# Enable HSTS to enforce HTTPS redirect at browser to eliminates HTTPS redirect time.
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
# Enable strong TLS encryption ciphers.
ssl_prefer_server_ciphers on;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
# Enable OCSP
ssl_stapling on;
ssl_stapling_verify on;
# Enable DNS resolver.
resolver 1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 valid=60s;
resolver_timeout 5s;